name: Deploy website on AWS S3

on:
  workflow_dispatch:
  
concurrency:
  group: "deploy on aws"
  cancel-in-progress: true

jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up python
        uses: actions/python@v2
        with:
          python-version: '3.x'

      - name: Install AWS CLI
        run: |
          pip install awscli
        
      - name: Configure credential
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_S3_REGION
        
      - name: Upload to S3
        run: |
          aws s3 cp ./index.html s3://$AWS_S3_BUCKET/
          aws s3 cp ./style.css s3://$AWS_S3_BUCKET/
          aws s3 sync ./assets s3://$AWS_S3_BUCKET/assets
